# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSystemtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_systemtest(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1440, 801)
    self.driver.find_element(By.ID, "logout").click()
    self.driver.find_element(By.ID, "email").send_keys("andrew.tran0508@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("GRx8bHAMNF@yw")
    self.driver.find_element(By.CSS_SELECTOR, ".registerButton").click()
    self.driver.find_element(By.ID, "logout").click()
    self.driver.find_element(By.ID, "email").send_keys("andrew.tran0508@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("GRx8bHAMNF@yw")
    self.driver.find_element(By.ID, "register").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("andrew.tran0508@gmail.com")
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("Andrew")
    self.driver.find_element(By.ID, "password1").click()
    self.driver.find_element(By.ID, "firstName").send_keys("andrew.tran0508@gmail.com")
    self.driver.find_element(By.ID, "password1").send_keys("GRx8bHAMNF@yw")
    self.driver.find_element(By.ID, "password2").click()
    self.driver.find_element(By.ID, "password1").click()
    self.driver.find_element(By.ID, "password1").click()
    element = self.driver.find_element(By.ID, "password1")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "password2").click()
    self.driver.find_element(By.ID, "password2").send_keys("http://127.0.0.1:5000/")
    self.driver.find_element(By.CSS_SELECTOR, ".registerButton").click()
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.ID, "email").send_keys("andrew.tran0508@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("GRx8bHAMNF@yw")
    self.driver.find_element(By.CSS_SELECTOR, ".registerButton").click()
    self.driver.find_element(By.ID, "input-field").click()
    self.driver.find_element(By.ID, "input-field").send_keys("hello")
    self.driver.find_element(By.ID, "input-field").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "input-field").send_keys("who is the highest scoring test cricketer")
    self.driver.find_element(By.ID, "input-field").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".bx-save").click()
    self.driver.find_element(By.ID, "history").click()
    self.driver.find_element(By.LINK_TEXT, "Chat Sun, 21 May 2023 20:52:15 GMT - You: hello").click()
    self.driver.find_element(By.ID, "logout").click()
    self.driver.find_element(By.ID, "email").send_keys("andrew.tran0508@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("GRx8bHAMNF@yw")
  
